[tools]
uv = "0.9"

[tasks.generate_proto]
description = "Generate Python code from Protobuf files"
run = """
rm -f src/uart_bridge/domain/proto/*_pb2.py
rm -f src/uart_bridge/domain/proto/*_pb2.pyi
protoc \
  --python_out=src/uart_bridge/domain/proto \
  --pyi_out=src/uart_bridge/domain/proto \
  --proto_path=../utils/proto \
  ../utils/proto/roboapp/*.proto
"""
sources = ["../utils/proto/roboapp/*.proto"]
outputs = [
  "src/uart_bridge/domain/proto/*_pb2.py",
  "src/uart_bridge/domain/proto/*_pb2.pyi"
]

[tasks.deps]
description = "Install and sync Python dependencies using uv for uart_bridge"
run = "uv sync"
sources = [
  "pyproject.toml",
  "uv.lock",
]
outputs = { auto = true }

[tasks.build]
depends = ["generate_proto", "deps"]

[tasks.lint]
depends = ["build"]
description = "Run Python linters and type checkers for uart_bridge"
run = ["uv run task lint", "uv run task check"]

[tasks.format]
depends = ["build"]
description = "Format Python code in uart_bridge using ruff"
run = "uv run task format"

[tasks.test]
depends = ["build"]
description = "Execute Python tests for uart_bridge"
run = "uv run task test"

[tasks.start]
depends = ["build"]
description = "Start the uart_bridge application"
run = "uv run python3 src/uart_bridge/main.py"
