#!/usr/bin/env bash
set -euo pipefail

echo "Cloning Submodules"
if [ "${GITHUB_ACTIONS:-}" != "true" ]; then
    git submodule update --init --recursive
fi

COMPONENT=${1:-all}

sudo echo "Install Dependencies for component: $COMPONENT"

# Setup repository
sudo mkdir -p /etc/apt/keyrings
if [ ! -f "/etc/apt/keyrings/zenoh-public-key.gpg" ]; then
	curl -L https://download.eclipse.org/zenoh/debian-repo/zenoh-public-key | sudo gpg --dearmor --yes --output /etc/apt/keyrings/zenoh-public-key.gpg
fi

if [ ! -f "/etc/apt/sources.list.d/zenoh.list" ]; then
	echo "deb [signed-by=/etc/apt/keyrings/zenoh-public-key.gpg] https://download.eclipse.org/zenoh/debian-repo/ /" | sudo tee /etc/apt/sources.list.d/zenoh.list >/dev/null
fi

sudo apt-get update

# Common
if [ "$COMPONENT" = "all" ] || [ "$COMPONENT" = "common" ] || [ "$COMPONENT" = "ui" ] || [ "$COMPONENT" = "camera" ] || [ "$COMPONENT" = "lidar" ] || [ "$COMPONENT" = "uart" ]; then
	sudo apt-get install -y \
		build-essential cmake ninja-build \
		libzenohc=1.6.2 libzenohc-dev=1.6.2 libzenohcpp-dev=1.6.2 zenohd

	sudo apt-mark hold libzenohc libzenohc-dev libzenohcpp-dev zenohd
	sudo systemctl disable zenohd --now || true
fi

# UI System
if [ "$COMPONENT" = "all" ] || [ "$COMPONENT" = "ui" ]; then
	sudo apt-get install -y \
		libwebkit2gtk-4.1-dev file libxdo-dev libssl-dev \
		libayatana-appindicator3-dev librsvg2-dev clang libclang-dev llvm llvm-dev
fi

# Main Camera System
if [ "$COMPONENT" = "all" ] || [ "$COMPONENT" = "camera" ]; then
	sudo apt-get install -y \
		nasm
fi

# Lidar System
if [ "$COMPONENT" = "all" ] || [ "$COMPONENT" = "lidar" ]; then
	sudo apt-get install -y \
		libgflags-dev libopencv-dev nlohmann-json3-dev \
		clang-tidy clang-format \
		libprotobuf-dev protobuf-compiler
fi

# UART Bridge
if [ "$COMPONENT" = "all" ] || [ "$COMPONENT" = "uart" ]; then
	sudo apt-get install -y \
		socat
fi
