name: Setup
description: "Setup mise dependencies"

inputs:
  workdir:
    description: "Working directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: jdx/mise-action@v3
      with:
        working_directory: ${{ inputs.workdir }}
