name: Setup
description: "Setup mise dependencies"
inputs:
  workdir:
    description: "Working directory"
    required: true
  component:
    description: "Component name (common, lidar, camera, uart, ui, minimal)"
    required: false
    default: "minimal"
runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@v3
    - uses: jdx/mise-action@v3
      with:
        working_directory: ${{ inputs.workdir }}
