# https://just.systems

target := './include ./src -regex ".*\.\(c\|h\|cpp\|hpp\)$"'

deps:
    cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

clang-tidy:
    find {{ target }} -exec clang-tidy -p ./build {} +;

format:
    find {{ target }} -exec clang-format -i {} +;

format-check:
    find {{ target }} -exec clang-format --Werror --dry-run -i {} +;

build:
    cmake --build build --config Release

[working-directory: 'build']
test:
    ctest --output-on-failure

