# https://just.systems

target := './include ./src -regex ".*\.\(c\|h\|cpp\|hpp\)"'

lint:
    find {{ target }} -exec clang-tidy -p ./build {} +;

format:
    find {{ target }} -exec clang-format -i {} +;

dry-format:
    find {{ target }} -exec clang-format --Werror --dry-run -i {} +;

build:
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build -j --config Release
