[env]
CMAKE_CXX_COMPILER_LAUNCHER = "sccache"
CMAKE_C_COMPILER_LAUNCHER = "sccache"

[tools]
just = "latest"
sccache = "latest"

[tasks.sync]
description = "Generate CMake build files using just and ninja"
run = "just deps"
sources = ["CMakeLists.txt", "src/**/*.cpp", "include/**/*/hpp"]
outputs = ["./build/build.ninja", "./build/compile_commands.json"]

[tasks.generate_proto]
description = "Generate C++ code from Protobuf files"
wait_for = ["sync"]
run = """
rm -f src/proto/*.pb.cc
rm -f src/proto/*.pb.h
protoc \
  --cpp_out=src/proto \
  --proto_path=../utils/proto \
  $(find ../utils/proto -name "*.proto")
"""
sources = ["../utils/proto/**/*.proto"]
outputs = ["src/proto/*.pb.cc", "src/proto/*.pb.h"]

[tasks.deps]
description = "Install dependencies and generate code"
depends = ["sync", "generate_proto"]

[tasks.build]
depends = ["deps"]
description = "Compile C++ applications (processor, sender, viewer)"
run = "just build"
sources = [
  "./build/build.ninja",
  "./build/compile_commands.json",
  "include/**/*.hpp",
  "src/**/*.cpp"
]
outputs = ["./build/processor", "./build/sender", "./build/viewer"]

[tasks.lint]
description = "Run C++ linters (clang-tidy) and format checks"
run = [{ tasks = ["clang_tidy", "format_check"] }]

[tasks.clang_tidy]
depends = ["deps"]
description = "Run static analysis with clang-tidy"
run = "just clang-tidy"

[tasks.format_check]
depends = ["deps"]
description = "Verify if C++ code follows the clang-format style"
run = "just format-check"

[tasks.format]
depends = ["deps"]
description = "Automatically format C++ code using clang-format"
run = "just format"

[tasks.test]
depends = ["build"]
description = "Execute C++ unit tests"
run = "just test"
