name: "Setup Rust Environment"
description: "Setup Rust Environment"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Compute Cargo.lock hash
      id: cargo-lock-hash
      shell: bash
      run: |
        HASH=$(sha256sum $WORKDIR/Cargo.lock | awk '{print $1}')
        echo "CARGO_LOCK_HASH=$HASH" >> $GITHUB_ENV
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ${{env.WORKDIR}}/target
        key: ${{ runner.os }}-cargo-${{ env.CARGO_LOCK_HASH }}
    - name: Install Dependencies
      shell: bash
      run: |
        cd "$WORKDIR"
        cargo fetch
