name: LiDAR System Check
on:
  pull_request:
    paths:
      - "lidar_system/**"
      - ".github/workflows/lidar_system_check.yaml"
env:
  WORKDIR: lidar_system
  SCCACHE_GHA_ENABLED: "true"
jobs:
  LiDAR_System_Check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/core-ma-king/roboapp/ci-image:latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1
      - name: Run sccache-action
        uses: mozilla-actions/sccache-action@v0.0.9
      - uses: ./.github/actions/mise
        with:
          workdir: ${{ env.WORKDIR }}
      - name: Install Dependencies
        run: |
          mise //${{ env.WORKDIR }}:deps
      - name: Build
        run: |
          mise //${{ env.WORKDIR }}:build
      - name: Lint
        run: |
          mise //${{ env.WORKDIR }}:lint
      - name: Test
        run: |
          mise //${{ env.WORKDIR }}:test
