name: Main Camera System Check
on:
  pull_request:
    paths:
      - "main_camera_system/**"
      - ".github/workflows/main_camera_system_check.yaml"
env:
  CARGO_TERM_COLOR: always
  WORKDIR: main_camera_system
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
jobs:
  MainCameraSystem_Check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/core-ma-king/roboapp/ci-image:latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 1
      - uses: ./.github/actions/mise
        with:
          workdir: ${{ env.WORKDIR }}
      - uses: ./.github/actions/rust
        with:
          workdir: ${{ env.WORKDIR }}
      - name: Install Dependencies
        run: |
          mise //${{ env.WORKDIR }}:deps
      - name: Lint
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Format
        run: |
          cargo fmt --all -- --check
      - name: Run Tests
        run: |
          cargo test --all-features -- --nocapture
