name: Main Camera System Cache

on:
  push:
    branches:
      - "main"
    paths:
      - "main_camera_system/src/**"
      - ".github/workflows/main_camera_system_cache.yaml"

env:
    CARGO_TERM_COLOR: always
    WORKDIR: main_camera_system

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          $WORKDIR/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('$WORKDIR/Cargo.lock') }}
    - name: Install Dependencies
      run: cargo fetch
      working-directory: $WORKDIR
