name: Markdown Check
on:
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/markdown.yaml"
jobs:
  Markdown_Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/mise
        with:
          workdir: .
      - name: Install Dependencies
        run: |
          mise //:markdown_lint
