name: Ui System Cache
on:
  push:
    branches:
      - "main"
    paths:
      - "ui_system/src/**"
      - ".github/workflows/ui_system_cache.yaml"
env:
  CARGO_TERM_COLOR: always
  WORKDIR: ui_system
jobs:
  UI_System_Cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/rust
        with:
          workdir: ${{ env.WORKDIR }}
